
export const reviews = [
    {
        id: 1,
        name: "Tom Leonard",
        location: "St. Armand Circle, Long Boat Key, FL",
        text: "We gave Festive Lighting Pros a unique challenge when we started this and we had over 100 trees in a park to light plus we wanted to create a ceiling over the park, create a sense of a ceiling or roof. They came up with an ingenious idea to stream cables across the bar and hung over one hundred spheres from these cables. It turned out magical. Everybody loves it. And it's been a pleasure to work with someone that can actually think outside the box.",
        rating: 5,
        avatar: "/reviews/Tom-Leonard.jpg",
    },
    {
        id: 2,
        name: "Austin York",
        location: "Sun Outdoors, Sarasota, FL",
        text: "Hi my name is Austin from Sun Outdoors Sarasota and we use Festive Lighting Pros for our holiday lighting needs. From the very beginning, Matt and his team are professional, timely, and courteous.",
        rating: 5,
        avatar: "/reviews/Austin-1.jpg",
    },
    {
        id: 3,
        name: "Mitch Good",
        location: "El Melvin Cocina Mexicana, Downtown Sarasota, FL",
        text: "I just want to give a quick shout out to Festive Lighting Pros. They've been with us for about a year now. They take care of all your maintenance. Our customers love it. We love it.",
        rating: 5,
        avatar: "/reviews/Mitch-Hood.jpg",
    },
    {
        id: 4,
        name: "Kelly Johnson",
        location: "Kia of Port Charlotte",
        text: "They (Festive Lighting Pros) were professional. They were quick, they installed everything with safety in mind, and you can see how beautiful the results are.",
        rating: 5,
        avatar: "/reviews/Kelly-Johnson.jpg",
    },
    {
        id: 5,
        name: "Jonnie and Tim Dwyer",
        location: "Lakewood Ranch, FL",
        text: "Festive Lighting Pros took away such tremendous stress by making our home look so beautiful for our grandchildren. The enchantment that they experienced was worth every penny. It gave us more time and more opportunities to enjoy the holidays rather than making it all work and Matt's installers, they were so professional.",
        rating: 5,
        avatar: "/reviews/Dwyers.jpg",
    },
    {
        id: 6,
        name: "Brad Gucciardo",
        location: "Bella Sole, Bradenton, FL",
        text: "They did an amazing job decorating my home to say that Festive Lighting Pros changed my entire attitude about Christmas specially this year is an understatement. This is incredible to come home to this every day is amazing. You will have a smile on your face, every morning every night when you come home.",
        rating: 5,
        avatar: "/reviews/Bob-Gucciardo.jpg",
    },
    {
        id: 7,
        name: "Dennis and Kathy Lasota",
        location: "Lakewood National Golf Course, Bradenton, FL",
        text: "This is our first year having our home completely decorated in the head Festival Lighting Pros. Take care of it for us. We were very pleased with the end results and it saved my back and perhaps a spill on the ladder. And we are excited to show off our house.",
        rating: 5,
        avatar: "/reviews/Lasotas.jpg",
    },
    {
        id: 8,
        name: "Neil Newsham",
        location: "Bradenton, FL",
        text: "I couldn't be more happy with the services provided by Festive Lighting Pros. They were very, very efficient, very, very professional, easy to deal with. We really liked the way our house turned out.",
        rating: 5,
        avatar: "/reviews/Newshams.jpg",
    },
    {
        id: 9,
        name: "Liz Hazeltine",
        location: "Sarasota, FL",
        text: "Hi, my name is Liz and we live in Sarasota. This was a new house and our first Christmas in it and we wanted it to look spectacular. So we hired Festive Lighting Pros and we got beyond our wildest dreams. They were easy to work with. And the house looks great and you can see for yourself.",
        rating: 5,
        avatar: "/reviews/Liz-Hazeltine.jpg",
    },
    {
        id: 10,
        name: "Darren and Amanda Arrington",
        location: "Miromar Lakes, Ft. Myers, FL",
        text: "We've been working with Festival Lighting Pros the last two years to come put up lights at our house . . . They suggest new things that we can add every year. We're a little bit biased, but we think we've got the best house in the neighborhood with lights and all the neighbors come by.",
        rating: 5,
        avatar: "/reviews/Arringtons.jpg",
    },
];